version: 2

sh-shellcheck: &sh-shellcheck
  lint-command: 'shellcheck -f gcc -x'
  lint-formats:
    - '%f:%l:%c: %trror: %m'
    - '%f:%l:%c: %tarning: %m'
    - '%f:%l:%c: %tote: %m'

any-writegood: &any-writegood
  lint-command: 'npx -q write-good --parse'
  lint-formats:
    - '%f:%l:%c:%m'

languages:
  sh:
    - <<: *sh-shellcheck

  pandoc:
    - <<: *any-writegood
