version: 2

sh-shellcheck: &sh-shellcheck
  lint-command: 'shellcheck -f gcc -x'
  lint-formats:
    - '%f:%l:%c: %trror: %m'
    - '%f:%l:%c: %tarning: %m'
    - '%f:%l:%c: %tote: %m'

languages:
  sh:
    - <<: *sh-shellcheck
