#!/bin/bash

source "$(dirname $0)"/logging.sh

karabiner_config_path="$HOME/Library/Application Support/Karabiner"

if [ -d "${karabiner_config_path}" ]; then
    source=$HOME/.karabiner/private.xml
    dest="${karabiner_config_path}/private.xml"

    log_info "Symlinking ~/.karabiner/private.xml to ~/Library/Application Support/private.xml"

    rm -rf "${dest}"
    ln -s ${source} "${dest}"
fi
